### PR TITLE
fix: fix download documentation as zip file

### LINKED ISSUE #105: Download documentation as zip file from playground page does not work
#### Describe the bug
I observed download action available in playground does no work. 

#### How to Reproduce
I have been using AsyncAPI Playground both from both official page:
- https://playground.asyncapi.io/
- and locally as docker (that I prepared based on https://github.com/asyncapi/playground instruction)
- taken from master: https://github.com/asyncapi/playground/commit/b8a94757562ad130903c2cbe75c37f7dab6db205
- I checked on different browsers, e.g. on Firefox window showed up and download takes forever: "Unknown time left" to download

#### Expected behavior
- it work some time ago and result was that proper zip file was generated

### PR DESCRIPTION
**Pull request by AceTheCreator**
**Description**

- ...
- ...
- ...

**Related issue(s)**
Fixes #105

### CODE REVIEW

**Review by derberg — DISMISSED** [review]
@AceTheCreator thanks for quick action! All good from my side. I checked out locally and performed manual test of downloaded zip file, lgtm

@fmvilas you can merge and deploy Franito 🍺

**Review by lukaszkowalik — DISMISSED** [review]
@AceTheCreator, I double checked your commit: I downloaded it and tested manually. It works. Thank you.

**Comment by derberg** [comment]
@AceTheCreator since this one is not yet merged, can you update in this PR also dependency to `@asyncapi/html-template` to latest `0.20.1`? there is just a small bug fix

**Comment by AceTheCreator** [comment]
> @AceTheCreator since this one is not yet merged, can you update in this PR also dependency to `@asyncapi/html-template` to latest `0.20.1`? there is just a small bug fix

@derberg sorry for the late reply tho, I was rounding up school exams. I'll get on it Asap.

**Review by derberg — APPROVED** [review]
thanks @AceTheCreator

**Pull request merged**
