### PR TITLE
feat: support v2.1.0 of spec

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Support for 2.1.0 version of spec:
- use latest version of html-template and markdown-template
- use latest version of converter - convert to 2.1.0:
  - inform about 2.1.0 version when user uses the 2.0.0 on every half hour - maybe to change to 1h?

Example with `2.0.0` version:

image

Example with `2.1.0` version:

image

**Related issue(s)**
Part of https://github.com/asyncapi/spec/issues/536

### CODE REVIEW

**Review by fmvilas — APPROVED** [review]
LGTM 🚀

**Comment by fmvilas** [comment]
There are some conflicts and checks failing.

**Comment by magicmatatjahu** [comment]
@fmvilas Thanks! Fixed!

**Review by fmvilas — DISMISSED** [review]

**Review by derberg — DISMISSED** [review]
looks awesome
I would only ping user once a day and not every 30min 😄

**Review by derberg — APPROVED** [review]

**Comment by magicmatatjahu** [comment]
Thanks folks! 🚀

**Pull request merged**
